### PR TITLE
Corrected the expression for the temperature change rate (control.f90).

### LINKED ISSUE #315: Temperature change per step in variable temperature MD
In variable temperature MD, the change of temperature at each step is wrongly calculated as the ratio between the cooling/heating rate and the time step, instead of the product. Therefore, the change per time step is wrong if the time step is not 1 fs.

`temp_change_step = md_variable_temperature_rate / mdl%timestep`

should be

`temp_change_step = md_variable_temperature_rate * mdl%timestep`

Sorry for the inconvenience.

### PR DESCRIPTION
**Pull request by AugustinLu**
Closes #315 

Correct definition of the change of temperature at each step in variable temperature MD simulations.

### CODE REVIEW

**Review by davidbowler — APPROVED** [review]
We should think about units for the variable temperature rate, maybe (I guess they will be K/fs by default: is that made clear anywhere?)

**Review by tsuyoshi38 — COMMENTED** [review]
I am sorry for asking the following now, but ..

Line 845-850:   "exit" instead of  "stop"?
If you want to stop here, please use "cq_abort".
If just "exit", calling "cq_warn" is better.

**Comment by AugustinLu** [comment]
> I am sorry for asking the following now, but ..
> 
> Line 845-850: "exit" instead of "stop"? If you want to stop here, please use "cq_abort". If just "exit", calling "cq_warn" is better.

The idea is that it should be a "failure" of the calculation and nothing should be calculated at all.
Therefore, `exit` should be replaced by a call to `cq_warn`, right?

Just to confirm, `exit` is the proper termination of CONQUEST -> Is it correct?

**Comment by tsuyoshi38** [comment]
Then, please use `cq_abort`.  
If you use `exit` here, it would just exit the do-loop, I think.

**Comment by AugustinLu** [comment]
> Then, please use `cq_abort`. If you use `exit` here, it would just exit the do-loop, I think.

You are right. I will update this.

**Pull request merged**
