### PR TITLE
Add extended XYZ file output for static run and structural optimization

### PR DESCRIPTION
**Pull request by JianboLin**
We have an option for output of extended-xyz file in run types of MD simulation.
But when we would like to check, save, or even visualize the atomic forces of specific geometry or during the structural optimization, add the same option in run types of static and structural optimization, would be convenient.

At present, from my tests, it works with static, cg, lbfgs, sqnm and also with cell optimization
detail in https://github.com/OrderN/CONQUEST-release/issues/305

### CODE REVIEW

**Review by davidbowler — COMMENTED** [review]
We have a variable `XYZfreq` (in `control.f90`) which is used to define how often this file is written out (at present only during MD, in `md_misc_module.f90`).  I wonder whether we should use it here: what do you think?

**Comment by JianboLin** [comment]
Thank you for your comment.
Static calculation or structural optimization (including opt cell ) may not have large number of steps, supposing several hundred steps.
And it may be also okay if we use default `XYZfreq=1`, in these run types (except static).

**Comment by tsuyoshi38** [comment]
> Thank you for your comment. Static calculation or structural optimization (including opt cell ) may not have large number of steps, supposing several hundred steps. 

I understand your point.

> And it may be also okay if we use default `XYZfreq=1`, in these run types (except static).

But, since it might help in some cases, could you do it?

**Comment by JianboLin** [comment]
Yes, updated in the latest commit. By the way, do we also to control output frequency of xsf file with `XSFfreq` in these types of run?

**Review by tsuyoshi38 — APPROVED** [review]

**Comment by JianboLin** [comment]
Thank you for your approval.

**Pull request merged**
