### PR TITLE
Release 1.4

### PR DESCRIPTION
**Pull request by davidbowler**
This will be the formal release of version 1.4

### CODE REVIEW

**Review by ayakon — APPROVED** [review]

**Comment by tsuyoshi38** [comment]
Now, I have a problem of compiling manual (make html) related to sphinx on my mac..  (sonoma 14.6.1)
Sorry, I don't understand what is happening, but please let me know whether you have any problem in doing "make html".

(I am now upgrading anaconda, but it takes time. I will check it again tomorrow.)

**Comment by AugustinLu** [comment]
> Now, I have a problem of compiling manual (make html) related to sphinx on my mac.. (sonoma 14.6.1) Sorry, I don't understand what is happening, but please let me know whether you have any problem in doing "make html".
> 
> (I am now upgrading anaconda, but it takes time. I will check it again tomorrow.)

If you are using the default environment of conda, some required packages to compile the manual are missing.
I had to install these: 
```
pip install sphinx_rtd_theme
pip install sphinxcontrib-bibtex
```
then `make html` worked without problem.

**Review by lionelalexandre — APPROVED** [review]

**Comment by tsuyoshi38** [comment]
> > Now, I have a problem of compiling manual (make html) related to sphinx on my mac.. (sonoma 14.6.1) Sorry, I don't understand what is happening, but please let me know whether you have any problem in doing "make html".
> > (I am now upgrading anaconda, but it takes time. I will check it again tomorrow.)
> 
> If you are using the default (base) environment of conda, some required packages to compile the manual are missing. I had to install these:
> 
> ```
> pip install sphinx_rtd_theme
> pip install sphinxcontrib-bibtex
> ```
> 
> then `make html` worked without problem.

Thank you very much for this comment. Now, I have succeeded to compile.

**Comment by tsuyoshi38** [comment]
I have  changed the default setting of Diag.BlockSizeR (and Diag.BlockSizeC) from this version. 
Should I issue a pull request to this branch (release-1.4) or to the develop first ?
The changed part in 'input_tags.rst' is the following. (I tried to attach the file here, but I can't.)
----
Diag.BlockSizeR (*integer*)
    Block size for rows (See next).
    From v1.4, the default value is 30 when Diag.PaddingHmatrix is true.
    It is recommended to check the efficiency (CPU time) on your platform by changing this value.
    Usually 20-30 is appropriate.
    
    *default*: 30 or Determined automatically (if Diag.PaddingHmatrix= true)
----

**Review by tsuyoshi38 — APPROVED** [review]

**Pull request merged**
