### PR TITLE
Documentation for installation on Ubuntu

### PR DESCRIPTION
**Pull request by AugustinLu**
Instructions have been added for compilation using Ubuntu.
(In #365 the latest commit had not yet been pushed to the repository..)

### CODE REVIEW

**Review by davidbowler — APPROVED** [review]
I have checked this (using Ubuntu on a Mac) and it all works very well.  The only slight issue at present is that your suggested system.make does not set the OMP_DUMMY flag explicitly - it might be worth adding this.

**Review by davidbowler — COMMENTED** [review]
Actually, now that I think about it, it might be better just to have a system.ubuntu.make file as part of this branch.

**Comment by AugustinLu** [comment]
> I have checked this (using Ubuntu on a Mac) and it all works very well. The only slight issue at present is that your suggested system.make does not set the OMP_DUMMY flag explicitly - it might be worth adding this.

> Actually, now that I think about it, it might be better just to have a system.ubuntu.make file as part of this branch.

Thank you for your suggestions. I will add the OMP_DUMMY flag and the system.ubuntu.make file.

**Comment by davidbowler** [comment]
Excellent! This looks very good - thank you.

**Pull request merged**
