### PR TITLE
Refactor the testsuite

### LINKED ISSUE #200: Refactor output checks in testsuite
We want to include rather than exclude keys from the output

### PR DESCRIPTION
**Pull request by tkoskela**
Closes #200

Each Fortran test now has its own parametrized python test that specifies the values it checks from the output. I would have liked to also make `results` a fixture, but I couldn't figure out how to pass the path into a fixture.

### CODE REVIEW

**Comment by davidbowler** [comment]
Can you update the README.md to reflect how we now create new tests, and in particular how we can specify a different precision to the default?

**Review by davidbowler — APPROVED** [review]

**Comment by tkoskela** [comment]
> Can you update the README.md to reflect how we now create new tests, and in particular how we can specify a different precision to the default?

Thanks, good point! I've done it, I hope this has made it a bit simpler to add tests as well.

In the future, you can select "request changes" in the review if you would like to request changes :smiley:

**Comment by davidbowler** [comment]
Can you add an example for how to set a precision that is not the default (or add it to the README.md)?

**Comment by tkoskela** [comment]
To set a custom precision I would maybe just modify the precision matching the key in the test function. Something like:

```
    @pytest.mark.parametrize("key", ['Harris-Foulkes energy',
                                     'Max force',
                                     'Force residual',
                                     'Total polarisation'])
    def test_003(self, key, default_precision, testsuite_directory):

        path = os.path.join(testsuite_directory, "test_003_bulk_BTO_polarisation")
        res = results(path, key)
        if key is 'Total polarisation':
          precision = custom_precision
        else
          precision = default precision
        np.testing.assert_allclose(res[0], res[1], rtol = precision, verbose = True)
```
Doing it through the fixtures seems too complicated

**Comment by davidbowler** [comment]
Could we also parametrize the precision in the same way as the key?

**Comment by tkoskela** [comment]
Yeah, I just realised we could. Then it can't be a fixture but I don't think that will matter.

**Comment by tkoskela** [comment]
You already merged this PR, do you want me to open another one?

**Pull request merged**
